name: Update Sequence
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: python3 update_sequence.py
